#!/usr/bin/env node

'use strict';

const sqlite3 = require('sqlite3');
const db = new sqlite3.Database('paquebot.db');

db.serialize(() => {
  db.run(`
    create table bestof (
      ts       varchar(17) primary key,
      added_by varchar(9),
      author   varchar(9),
      message  text
    ) without rowid
  `);

  db.run(`
    create table stats (
      type varchar(15),
      name varchar(32),
      hits int          default 1,
      primary key (type, name)
    ) without rowid
  `);
});

db.close();
